/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_barismeral_jni_Mat */

#ifndef _Included_com_github_barismeral_jni_Mat
#define _Included_com_github_barismeral_jni_Mat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_barismeral_jni_Mat
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_barismeral_jni_Mat_plus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_barismeral_jni_Mat
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_barismeral_jni_Mat_minus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_barismeral_jni_Mat
 * Method:    div
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_barismeral_jni_Mat_div
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_barismeral_jni_Mat
 * Method:    multi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_barismeral_jni_Mat_multi
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
